### ISSUE TITLE
Version 0.3.8 ?

### ISSUE THREAD

**Issue by MarcoPolo** [Pauan/rust-signals#10]
It would be great to get another version up on crates with at least this change https://github.com/Pauan/rust-signals/commit/b1e69ffffdf6a4e6ce4b35cd0158514fd9b39bc1

thanks

**Comment by Pauan** [comment]
Yeah, I've been wanting to publish a new version, but it's complicated because of #8, since that means I need to bump the major version.

**Comment by MarcoPolo** [comment]
That's makes sense. Thanks!

**Comment by Pauan** [comment]
I temporarily reverted #8 and published version `0.3.8`
