### ISSUE TITLE
'FRP', the actor model, and the Signals project

### ISSUE THREAD

**Issue by kellytk** [Pauan/rust-signals#11]
I've had a thought recently: The actor model is a hack to handle concurrency that becomes obsolete with proper tools to address concurrency's issues such as async/await, `Future`s+runtime, and other language and ecosystem synchronization features.

I'd be interested to see actor-style supervision hierarchies, ('self-healing') first-class, generalized and ordered communication (messages) between [local/remote] actors, and eventual-consitency state (eg., raft) as separate Future-based crates which do not assume an actor model.

Is there any particular reason why experiments of the above kind couldn't be performed together with the Signals project if one wanted to stay close to `Future`s whilst writing code in an 'FRP' style?

**Comment by Pauan** [comment]
I think actors and signals are basically completely unrelated. FRP is also completely unrelated to actors, it's a different paradigm entirely.

An actor is basically just a [`Sink`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/sink/trait.Sink.html) which allows it to receive messages. That's pretty much it.

I think [`Stream`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/stream/trait.Stream.html)s are a lot better than actors. They're simpler, and composable.

All of the things you mentioned are things that would be handled by `Stream`, not `Signal` (it doesn't really make sense to talk about them for `Signal`).

Here is an example of a supervision hierarchy with `Stream`s:

```rust
loop {
    let result = spawn_some_task().try_for_each(|message| {
        // Handle message...
    }).await;

    match result {
        Ok(()) => {
            // The task finished and did not error...
            break;
        },
        Err(e) => {
            // Handle error from task...
        },
    }
}
```

The above loop will keep respawning the subtask if it fails.

As for "first-class, generalized and ordered communication", that's exactly what `Stream` is. It sounds like you're not really looking for FRP, you're looking for [streams](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/stream/index.html).
