### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by onehundredfeet** [Pauan/rust-signals#25]
Hi Folks,

Really interested in using your crate. I've looked through the tests and they are helpful, but some documented examples would be amazing. Your docs exposed a lot more functionality than I thought existed. 

I would love to see how you would implement the examples on https://docs.rs/reactive-rs/0.1.1/reactive_rs/ for example.

Cheers,
Ryan.

**Comment by Pauan** [comment]
We now have [a tutorial](https://docs.rs/futures-signals/%5E0.3.21/futures_signals/tutorial/index.html), and some examples have also been added to the docs.
