### ISSUE TITLE
Is there a way to avoid unnecessary Arc cloning inside a map_ref?

### ISSUE THREAD

**Issue by CyrusAlbright** [Pauan/rust-signals#56]
In a program I'm working on, an Arc with many common resources is passed around. In some of the reactive tasks I'm making with the SignalExt::for_each() trait method, it is necessary to be able to access this Arc, so I zip it into another Signal with the map_ref macro. This ends up looking like this:
```rs
struct GlobalState;

let global_state = std::sync::Arc::new(GlobalState);

let some_mutable = Mutable::new(0);

let combined_signal = futures_signals::map_ref! {
	let some = mutable.signal(),
	let global_state = futures_signals::signal::always(global_state.clone()) =>
	(*some, global_state)
};
// then do things with the combined_signal
```

This doesn't compile, because the reference to the Arc doesn't live long enough. So to get it to compile, I have to change it to this:
```rs
let combined_signal = futures_signals::map_ref! {
	let some = mutable.signal(),
	let global_state = futures_signals::signal::always(global_state.clone()) =>
	(*some, global_state.clone())
};
```

This clones the Arc every time the mutable signal changes, which is possibly very expensive. Is there a better way to do this that I'm not aware of, or is this the best I can do with the library as-is?

If I'm not mistaken, it should be theoretically possible for the global_state signal which never changes to just store a single Arc and hand out references to it whenever necessary, instead of needing to clone every time. I haven't looked into the soundness super thoroughly, but I just think that this is unnecessarily painful for what is possibly a straightforward and simple change.

**Comment by CyrusAlbright** [comment]
Just to be clear, cloning an Arc, especially unnecessarily, actually can be very expensive (and as with most things in performance, benchmarking it in isolation will never tell you this), because it's a guaranteed cache miss and an atomic operation (and on some platforms potentially a lock). It's definitely not the same as "just incrementing a number," as you phrased it. In languages like Swift where nearly everything is atomically reference counted, Arc increments and decrements can take up a huge proportion of running program time at around 32% in real use cases (not microbenchmarks).

Second, I was not aware that it was possible to do this with map_ref. Is it possible to better document this in the map_ref macro page? Macros, especially nested macros, are famously hard to decode from the outside.

As to why I'm doing it, it's because I run into **the exact same issue** if I do SignalExt::for_each() on a signal and need to access the Arc inside the for_each, namely that it needs to clone the Arc every time in order to compile. I was looking for a way to avoid this.

**Comment by Pauan** [comment]
For fun, I tried benchmarking the full Signal + Futures executor system:

```
Signal futures      time:   [73.912 ns 74.170 ns 74.396 ns]
Signal async-std    time:   [76.064 ns 76.193 ns 76.342 ns]
Signal smol         time:   [72.263 ns 72.640 ns 73.088 ns]
```

This is just updating a single Mutable, and then receiving the Signal update using a `for_each`, so it's pretty much the simplest thing you can do:

```rust
let m = Mutable::new(5);
let s = m.signal();

{
    let mut l = m.lock_mut();
    *l += 1;
}

s.for_each(|_value| { async {} })
```

And it's 46 times slower than a fetch-add. Of course 72 ns is still absurdly fast, that's only 0.000072 milliseconds. That's suitable for any situation other than the most hardcore embedded systems.

If you're curious, here is the [benchmark code](https://gist.github.com/Pauan/404f88d4945e14ebf7ecc509ac5a377b) I used.

**Comment by Pauan** [comment]
By the way, I want to make one thing very clear: even if you *are* using multi-threading in your program, as long as your `global_state` is not being used in multiple threads, then you can use `Rc` for the `global_state`.

Rust has super-fine-grained multithreading, you can have some parts of your program multi-threaded and some parts not. The compiler will prevent you from accidentally using an `Rc` across multiple threads, so it can only be used within the thread where it is created.

And most Future executors allow for running non-`Send` Futures. For example in the [`futures` crate](https://docs.rs/futures/0.3.21/futures/task/trait.LocalSpawnExt.html#method.spawn_local) and the [`wasm-bindgen-futures` crate](https://docs.rs/wasm-bindgen-futures/0.4.30/wasm_bindgen_futures/fn.spawn_local.html). So there's no issue with using `Rc`, you only need `Arc` if you're actually sending that specific value across multiple threads.
