### ISSUE TITLE
Error on spawning a signal with `wasm_bindgen_futures::spawn_local`

### ISSUE THREAD

**Issue by limira** [Pauan/rust-signals#6]
Hi,
I am still a noob at Rust's `future`, I'm sorry if this is not actually an issue.

I try this:
```rust
use futures_signals::signal::{Mutable, SignalExt};
use futures_util::future::ready;

use wasm_bindgen_futures::spawn_local;

fn main() {
    let value = Mutable::new(42);
    let future = value.signal().for_each(|v| {
        println!("Value = {}", v);
        ready(())
    });
    spawn_local(future);
}
```
Compile with `cargo +nightly build --target=wasm32-unknown-unknown` give the error:
```
error[E0277]: the trait bound `futures_signals::signal::signal::ForEach<futures_signals::signal::mutable::MutableSignal<{integer}>, futures_util::future::ready::Ready<()>, [closure@src/main.rs:8:42: 11:6]>: futures::future::Future` is not satisfied
  --> src/main.rs:12:5
   |
12 |     spawn_local(future);
   |     ^^^^^^^^^^^ the trait `futures::future::Future` is not implemented for `futures_signals::signal::signal::ForEach<futures_signals::signal::mutable::MutableSignal<{integer}>, futures_util::future::ready::Ready<()>, [closure@src/main.rs:8:42: 11:6]>`
   |
   = note: required by `wasm_bindgen_futures::spawn_local`
```
Rust version:
```
rustc +nightly --version
rustc 1.36.0-nightly (7d5aa4332 2019-05-16)
```
What I need to do to solve this error?
Thanks!

**Comment by Pauan** [comment]
That's a good question.

There is currently a split between the old style Futures 0.1, and the new Futures 0.3

Futures 0.3 is based on the official `Future` trait. So people are expected to slowly migrate over to Futures 0.3

The `wasm-bindgen-futures` crate was designed for Futures 0.1, so it's not compatible with Futures 0.3. However, I recently added in Futures 0.3 support to `wasm-bindgen-futures`.

You can use it by enabling the `futures_0_3` feature in your `Cargo.toml`:

```toml
wasm-bindgen-futures = { version = "0.3.21", features = ["futures_0_3"] }
```

Now you can import the `futures_0_3` submodule and use it:

```rust
use wasm_bindgen_futures::futures_0_3::spawn_local;
```

**Comment by limira** [comment]
It works! Thank you very much!
