### ISSUE TITLE
Enabling Gitter chat support

### ISSUE THREAD

**Issue by kellytk** [Pauan/rust-signals#7]
Please consider enabling [Gitter chat support](https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/rooms.md#room-creation) for this repo as well as https://github.com/Pauan/rust-dominator.

**Comment by Pauan** [comment]
Is there a benefit to that? Right now there aren't very many users for Signals.

(And it seems people have mostly moved over to Discord, including Rust itself)

**Comment by kellytk** [comment]
I've spoken with several others on Gitter that are interested in both Signals and Dominator.  While Discord is popular, quite a few people either can't or won't use it.

**Comment by Pauan** [comment]
I'm curious: if they want to discuss things, why aren't they doing so in the Issues?

As for Gitter specifically, I don't have anything against it (I've used it in the past), but I really don't want to create any fragmentation, so I would rather use whatever Rust (and the Rust Wasm WG) is using, which is currently Discord.
